services:
  - type: web
    name: acme-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: |
      python manage.py migrate && \
      python manage.py collectstatic --noinput && \
      honcho -f Procfile.web start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: acme-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: acme-redis-6ui8      # IMPORTANT: must match your Redis name
          type: redis
          property: connectionString

  - type: redis
    name: acme-redis-6ui8             # IMPORTANT: must match your Redis name
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

databases:
  - name: acme-db
    plan: free
