services:
  - type: web
    name: acme-web
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: honcho -f Procfile.web start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: acme-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: acme-redis
          type: redis
          property: connectionString

  - type: redis
    name: acme-redis
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all

databases:
  - name: acme-db
    plan: free
